import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/contexts/themeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} dark:bg-darkBlue dark:text-white font-opensans`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
